# Generated by Django 3.1.4 on 2021-01-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
